Repository stephane1809/NutriRank, pull requests merged in 2023-10, with the labels that each got.

#1 ranking view complete
  NutriRank.xcodeproj/project.pbxproj
  NutriRank.xcodeproj/xcuserdata/gabrielsantiago.xcuserdatad/xcschemes/xcschememanagement.plist
  NutriRank/Assets.xcassets/DefaultBackgroundColor.colorset/Contents.json
  NutriRank/Assets.xcassets/DefaultCardColor.colorset/Contents.json
  NutriRank/Assets.xcassets/DefaultRankingCellColor.colorset/Contents.json
  NutriRank/Assets.xcassets/FirstPlaceRanking.colorset/Contents.json
  NutriRank/Assets.xcassets/SecondPlaceRanking.colorset/Contents.json
  NutriRank/Assets.xcassets/ThirdPlaceRanking.colorset/Contents.json
  NutriRank/Assets.xcassets/UserMockImage.imageset/Contents.json
  NutriRank/Assets.xcassets/UserMockImage.imageset/images-2.png
  NutriRank/ContentView.swift
  NutriRank/Presentation/ChallengeGroup/Views/RankingView/RankingCardComponent.swift
  NutriRank/Presentation/ChallengeGroup/Views/RankingView/RankingCellComponent.swift
  NutriRank/Presentation/ChallengeGroup/Views/RankingView/RankingMockedViewModel.swift
  NutriRank/Presentation/ChallengeGroup/Views/RankingView/RankingView.swift
Labels: enhancement

#4 Feature/create member usecases
  NutriRank.xcodeproj/project.pbxproj
  NutriRank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NutriRank.xcodeproj/xcuserdata/gabrielsantiago.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  NutriRank/Data/NutriRankMemberClient.swift
  NutriRank/Domain/Repositories/ChallengeMemberRepository.swift
  NutriRank/Domain/UseCases/Member/CreateChallengeMemberUseCase.swift
  NutriRank/Domain/UseCases/Member/FetchChallengeMemberUseCase.swift
  NutriRank/Domain/UseCases/Member/UpdateChallengeMemberUseCase.swift
  NutriRank/Factory/ChallengeGroupFactory.swift
  NutriRank/NutriRankApp.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: enhancement

#3 Refactoring Entities
  NutriRank.xcodeproj/project.pbxproj
  NutriRank/Assets.xcassets/Light Blue.colorset/Contents.json
  NutriRank/Data/NutriRankClient.swift
  NutriRank/Data/NutriRankClientPosts.swift
  NutriRank/Domain/Entities/ChallengeGroup/ChallengeGroup.swift
  NutriRank/Domain/Entities/ChallengeGroup/Member.swift
  NutriRank/Domain/Entities/ChallengeGroup/Post.swift
  NutriRank/Domain/Entities/ChallengeGroup/PostComment.swift
  NutriRank/Domain/Repositories/ChallengeGroupRepository.swift
  NutriRank/Domain/UseCases/Group/FetchGroupsUseCase.swift
  NutriRank/Factory/ChallengeGroupFactory.swift
  NutriRank/Info.plist
  NutriRank/NutriRankApp.swift
  NutriRank/Presentation/ChallengeGroup/Views/CreateGroupView.swift
  NutriRank/Presentation/ChallengeGroup/Views/GroupView.swift
  NutriRank/Presentation/View/FeedGroupView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: refactoring

#10 Feature/add safety to creation options
  NutriRank/Presentation/ChallengeGroup/Views/CreateGroupView.swift
  NutriRank/Presentation/ChallengeGroup/Views/CreateProfileView.swift
Labels: enhancement

#9 Link to invite
  NutriRank.xcodeproj/xcshareddata/xcschemes/NutriRank.xcscheme
  NutriRank.xcodeproj/xcuserdata/paulohenriquegomesdasilva.xcuserdatad/xcschemes/xcschememanagement.plist
  NutriRank/Factory/ChallengeGroupFactory.swift
  NutriRank/Presentation/ChallengeGroup/Views/GroupView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: enhancement

#13 Creating Post
  NutriRank/Domain/Entities/ChallengeGroup/ChallengeGroup.swift
  NutriRank/Domain/Entities/ChallengeGroup/Post.swift
  NutriRank/Domain/Repositories/ChallengeMemberRepository.swift
  NutriRank/NutriRankApp.swift
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/SheetCreatePostView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: enhancement

#17 Feature/implement logic in ranking view
  NutriRank/Presentation/ChallengeGroup/Views/RankingView/RankingCellComponent.swift
  NutriRank/Presentation/ChallengeGroup/Views/RankingView/RankingView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: enhancement

#20 Add member to group
  NutriRank.xcodeproj/project.pbxproj
  NutriRank.xcodeproj/xcuserdata/paulohenriquegomesdasilva.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  NutriRank/Data/NutriRankClient.swift
  NutriRank/Domain/Repositories/ChallengeGroupRepository.swift
  NutriRank/Domain/UseCases/Group/FetchGroupByMemberUseCase.swift
  NutriRank/Factory/ChallengeGroupFactory.swift
  NutriRank/Factory/FeedPostViewFactory.swift
  NutriRank/Factory/FirstTimeUsingAppFactory.swift
  NutriRank/NutriRankApp.swift
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/SheetCreatePostView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: refactoring

#26 Button to enter in group using ID
  NutriRank/Data/NutriRankClient.swift
  NutriRank/Presentation/ChallengeGroup/Views/CreateGroupView.swift
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
  NutriRank/Presentation/ChallengeGroup/Views/GroupView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: enhancement

#28 hotfix: bug fetch group
  NutriRank.xcodeproj/project.pbxproj
  NutriRank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: bug

#30 Hotfix/fetch group bug
  NutriRank.xcodeproj/project.pbxproj
  NutriRank/Data/NutriRankClient.swift
  NutriRank/Domain/Repositories/ChallengeMemberRepository.swift
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
Labels: bug

#31 Hotfix
  NutriRank.xcodeproj/project.pbxproj
  NutriRank.xcodeproj/xcuserdata/paulohenriquegomesdasilva.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  NutriRank/Data/NutriRankClientPosts.swift
  NutriRank/NutriRank.entitlements
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/SheetPostView.swift
Labels: bug

#32 Hotfix
  NutriRank.xcodeproj/project.pbxproj
  NutriRank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NutriRank.xcodeproj/xcuserdata/paulohenriquegomesdasilva.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  NutriRank/Data/NutriRankClient.swift
  NutriRank/Data/NutriRankClientPosts.swift
  NutriRank/Domain/Repositories/ChallengeMemberRepository.swift
  NutriRank/NutriRank.entitlements
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/SheetPostView.swift
  NutriRank/Presentation/ViewModel/FeedGroupViewModel.swift
Labels: bug

#35 Refactoring
  NutriRank/Presentation/ChallengeGroup/Views/CreateProfileView.swift
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
Labels: refactoring

#38 ranking issue temporarely fixed (nuvem problem)
  NutriRank.xcodeproj/xcuserdata/gabrielsantiago.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  NutriRank/Data/NutriRankClient.swift
Labels: bug

#37 Hotfix: Navigation
  NutriRank/Presentation/ChallengeGroup/Views/CreateProfileView.swift
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/OnboardingView.swift
Labels: bug

#40 Hotfix: navigation stacks
  NutriRank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NutriRank/Presentation/ChallengeGroup/Views/CreateProfileView.swift
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
Labels: bug

#41 hotfix: navigation stacks
  NutriRank/NutriRankApp.swift
  NutriRank/Presentation/ChallengeGroup/Views/EmptyStateView.swift
  NutriRank/Presentation/ChallengeGroup/Views/OnboardingView.swift
Labels: bug

#42 Feature/ajust ranking view presentation
  NutriRank.xcodeproj/xcuserdata/gabrielsantiago.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/RankingView/RankingCellComponent.swift
Labels: enhancement

#44 Hotfix Sheet Post View
  NutriRank/Presentation/ChallengeGroup/Views/FeedPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/PostsView/CardPostView.swift
  NutriRank/Presentation/ChallengeGroup/Views/SheetPostView.swift
Labels: bug
